name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: clintt/fastapi-app:latest

      - name: Deploy to AWS EC2
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
          chmod 400 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_IP }} "
            docker pull clintt/fastapi-app:latest
            docker-compose down
            docker-compose up -d
          "